### ISSUE TITLE
Calculator Currently Unusable

### ISSUE THREAD

**Issue by MrCSoldier** [Pronner/CSharp_Calculator#1]
Please understand that i am only point out the mistakes as you have to learn from them.
- Unused Functions
- Too many white spaces flooding the file making more lines than there should be
- Too many if statements.
- Project is missing the file named Program.cs (cannot be debugged using Visual Studio)
- I have to literally use a key/Serial Key to use the calculator. Make your own UI. Don't use a third-party software or application.
- literally unusable.
- There's literally no processing involved (You are either developing it, or that 3rd-party software does the processing or you forgot to make it).

Things that are actually good.
- Used Switch-Case Statement

**Comment by Pronner** [comment]
I'm aware of all of those problems

I've actually abandoned this repository
I was creating it to understand some more things in code and this was a side project that I'd develop when I was bored or had nothing to do. However, if you are interested you can check out my other projects on my GitHub page or my GitHub organization.

[https://github.com/AIPALLC] << My organization.

Also, the too many if statements part isn't a problem...
